name: CI / Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Viktig: eksplisitte permissions for trygg kjøring og OIDC senere
permissions:
  contents: read
  packages: read
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (dev)
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Gjør Prisma robust i CI (SQLite). Kjører migrasjoner bare hvis de finnes.
      - name: Prepare Prisma (SQLite)
        run: |
          npx prisma generate
          if [ -d "prisma/migrations" ]; then
            npx prisma migrate deploy || true
          fi

      - name: Build app
        run: npm run build

      # Legg inn tester senere om du vil (npm test)
      # - name: Test
      #   run: npm test
