name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  node-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install (npm ci)
        run: npm ci

      - name: Prisma generate (if schema exists)
        run: |
          if [ -f prisma/schema.prisma ]; then
            npx prisma generate
          fi

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build
